module TestHelperFunctions

open TestData
open Microsoft.VisualStudio.TestTools.UnitTesting


let segmentName segment =
    if      segment = pixel00   then "pixel00"
    else if segment = pixel01   then "pixel01"
    else if segment = pixel10   then "pixel10"
    else if segment = pixel11   then "pixel11"
    else if segment = segment01 then "segment01"
    else if segment = segment02 then "segment02"
    else if segment = segment03 then "segment03"
    else if segment = segment04 then "segment04"
    else if segment = segment05 then "segment05"
    else if segment = segment06 then "segment06"
    else if segment = segment07 then "segment07"
    else if segment = segment08 then "segment08"
    else if segment = segment09 then "segment09"
    else if segment = segment10 then "segment10"
    else if segment = segment11 then "segment11"
    else if segment = segment12 then "segment12"
    else if segment = segment13 then "segment13"
    else if segment = segment14 then "segment14"
    else if segment = segment15 then "segment15"
    else if segment = segment16 then "segment16"
    else if segment = segment17 then "segment17"
    else if segment = segment18 then "segment18"
    else if segment = segment19 then "segment19"
    else if segment = segment20 then "segment20"
    else if segment = segment21 then "segment21"
    else if segment = segment22 then "segment22"
    else if segment = segment23 then "segment23"
    else if segment = segment24 then "segment24"
    else if segment = segment25 then "segment25"
    else if segment = segment26 then "segment26"
    else if segment = segment27 then "segment27"
    else if segment = segment28 then "segment28"
    else if segment = segment29 then "segment29"
    else if segment = segment30 then "segment30"
    else if segment = segment31 then "segment31"
    else if segment = segment32 then "segment32"
    else if segment = segment33 then "segment33"
    else if segment = segment34 then "segment34"
    else if segment = segment35 then "segment35"
    else if segment = segment36 then "segment36"
    else if segment = segment37 then "segment37"
    else if segment = segment38 then "segment38"
    else if segment = segment39 then "segment39"
    else if segment = segment40 then "segment40"
    else if segment = segment41 then "segment41"
    else if segment = segment42 then "segment42"
    else if segment = segment43 then "segment43"
    else if segment = segment44 then "segment44"
    else if segment = segment45 then "segment45"
    else if segment = segment46 then "segment46"
    else if segment = segment47 then "segment47"
    else if segment = segment48 then "segment48"
    else if segment = segment49 then "segment49"
    else if segment = segment50 then "segment50"
    else if segment = segment51 then "segment51"
    else if segment = segment52 then "segment52"
    else if segment = segment53 then "segment53"
    else if segment = segment54 then "segment54"
    else if segment = segment55 then "segment55"
    else if segment = segment56 then "segment56"
    else if segment = segment57 then "segment57"
    else if segment = segment58 then "segment58"
    else if segment = segment59 then "segment59"
    else if segment = segment60 then "segment60"
    else if segment = segment61 then "segment61"
    else if segment = segment62 then "segment62"
    else if segment = segment63 then "segment63"
    else if segment = segment64 then "segment64"
    else if segment = segment65 then "segment65"
    else if segment = segment66 then "segment66"
    else if segment = segment67 then "segment67"
    else if segment = segment68 then "segment68"
    else if segment = segment69 then "segment69"
    else if segment = segment70 then "segment70"
    else if segment = segment71 then "segment71"
    else if segment = segment72 then "segment72"
    else if segment = segment73 then "segment73"
    else if segment = segment74 then "segment74"
    else if segment = segment75 then "segment75"
    else if segment = segment76 then "segment76"
    else if segment = segment77 then "segment77"
    else if segment = segment78 then "segment78"
    else if segment = segment79 then "segment79"
    else if segment = segment80 then "segment80"
    else if segment = segment81 then "segment81"
    else if segment = segment82 then "segment82"
    else if segment = segment83 then "segment83"
    else if segment = segment84 then "segment84"
    else if segment = segment85 then "segment85"
    else if segment = segment86 then "segment86"
    else if segment = segment87 then "segment87"
    else if segment = segment88 then "segment88"
    else if segment = segment89 then "segment89"
    else if segment = segment90 then "segment90"
    else if segment = segment91 then "segment91"
    else if segment = segment92 then "segment92"
    else if segment = segment93 then "segment93"
    else if segment = segment94 then "segment94"
    else if segment = segment95 then "segment95"
    else if segment = segment96 then "segment96"
    else if segment = segment97 then "segment97"
    else if segment = segment98 then "segment98"
    else if segment = segment99 then "segment99"
    else if segment = segment100 then "segment100"
    else if segment = segment101 then "segment101"
    else if segment = segment102 then "segment102"
    else if segment = segment103 then "segment103"
    else if segment = segment104 then "segment104"
    else if segment = segment105 then "segment105"
    else if segment = segment106 then "segment106"
    else if segment = segment107 then "segment107"
    else if segment = segment108 then "segment108"
    else if segment = segment109 then "segment109"
    else if segment = segment110 then "segment110"
    else if segment = segment111 then "segment111"
    else if segment = segment112 then "segment112"
    else if segment = segment113 then "segment113"
    else if segment = segment114 then "segment114"
    else if segment = segment115 then "segment115"
    else if segment = segment116 then "segment116"
    else if segment = segment117 then "segment117"
    else if segment = segment118 then "segment118"
    else if segment = segment119 then "segment119"
    else if segment = segment120 then "segment120"
    else raise (System.Exception("unknown segment"))

let printMap mapA =
    let elements =
        Map.toList mapA
        |> List.map (fun (k,v) -> "(" + (segmentName k) + "," + (segmentName v) + ")")
        |> String.concat ";"
    "Map [" + elements + "]"

let segmentationName segmentation =
    if      segmentation = segmentation00 then "segmentation00"
    else if segmentation = segmentation01 then "segmentation01"
    else if segmentation = segmentation02 then "segmentation02"
    else if segmentation = segmentation03 then "segmentation03"
    else if segmentation = segmentation04 then "segmentation04"
    else if segmentation = segmentation05 then "segmentation05"
    else if segmentation = segmentation06 then "segmentation06"
    else if segmentation = segmentation07 then "segmentation07"
    else if segmentation = segmentation08 then "segmentation08"
    else if segmentation = segmentation09 then "segmentation09"
    else if segmentation = segmentation10 then "segmentation10"
    else if segmentation = segmentation11 then "segmentation11"
    else if segmentation = segmentation12 then "segmentation12"
    else if segmentation = segmentation13 then "segmentation13"
    else if segmentation = segmentation14 then "segmentation14"
    else if segmentation = segmentation15 then "segmentation15"
    else if segmentation = segmentation16 then "segmentation16"
    else if segmentation = segmentation17 then "segmentation17"
    else if segmentation = segmentation18 then "segmentation18"
    else if segmentation = segmentation19 then "segmentation19"
    else if segmentation = segmentation20 then "segmentation20"
    else if segmentation = segmentation21 then "segmentation21"
    else if segmentation = segmentation22 then "segmentation22"
    else if segmentation = segmentation23 then "segmentation23"
    else if segmentation = segmentation24 then "segmentation24"
    else if segmentation = segmentation25 then "segmentation25"
    else if segmentation = segmentation26 then "segmentation26"
    else if segmentation = segmentation27 then "segmentation27"
    else if segmentation = segmentation28 then "segmentation28"
    else if segmentation = segmentation29 then "segmentation29"
    else if segmentation = segmentation30 then "segmentation30"
    else if segmentation = segmentation31 then "segmentation31"
    else if segmentation = segmentation32 then "segmentation32"
    else if segmentation = segmentation33 then "segmentation33"
    else if segmentation = segmentation34 then "segmentation34"
    else if segmentation = segmentation35 then "segmentation35"
    else if segmentation = segmentation36 then "segmentation36"
    else if segmentation = segmentation37 then "segmentation37"
    else if segmentation = segmentation38 then "segmentation38"
    else if segmentation = segmentation39 then "segmentation39"
    else if segmentation = segmentation40 then "segmentation40"
    else if segmentation = segmentation41 then "segmentation41"
    else if segmentation = segmentation42 then "segmentation42"
    else if segmentation = segmentation43 then "segmentation43"
    else if segmentation = segmentation44 then "segmentation44"
    else if segmentation = segmentation45 then "segmentation45"
    else if segmentation = segmentation46 then "segmentation46"
    else if segmentation = segmentation47 then "segmentation47"
    else if segmentation = segmentation48 then "segmentation48"
    else if segmentation = segmentation49 then "segmentation49"
    else if segmentation = segmentation50 then "segmentation50"
    else if segmentation = segmentation51 then "segmentation51"
    else if segmentation = segmentation52 then "segmentation52"
    else if segmentation = segmentation53 then "segmentation53"
    else if segmentation = segmentation54 then "segmentation54"
    else if segmentation = segmentation55 then "segmentation55"
    else if segmentation = segmentation56 then "segmentation56"
    else if segmentation = segmentation57 then "segmentation57"
    else if segmentation = segmentation58 then "segmentation58"
    else if segmentation = segmentation59 then "segmentation59"
    else if segmentation = segmentation60 then "segmentation60"
    else if segmentation = segmentation61 then "segmentation61"
    else if segmentation = segmentation62 then "segmentation62"
    else if segmentation = segmentation63 then "segmentation63"
    else if segmentation = segmentation64 then "segmentation64"
    else if segmentation = segmentation65 then "segmentation65"
    else if segmentation = segmentation66 then "segmentation66"
    else if segmentation = segmentation67 then "segmentation67"
    else if segmentation = segmentation68 then "segmentation68"
    else if segmentation = segmentation69 then "segmentation69"
    else if segmentation = segmentation70 then "segmentation70"
    else if segmentation = segmentation71 then "segmentation71"
    else if segmentation = segmentation72 then "segmentation72"
    else if segmentation = segmentation73 then "segmentation73"
    else if segmentation = segmentation74 then "segmentation74"
    else if segmentation = segmentation75 then "segmentation75"
    else if segmentation = segmentation76 then "segmentation76"
    else if segmentation = segmentation77 then "segmentation77"
    else if segmentation = segmentation78 then "segmentation78"
    else if segmentation = segmentation79 then "segmentation79"
    else if segmentation = segmentation80 then "segmentation80"
    else if segmentation = segmentation81 then "segmentation81"
    else if segmentation = segmentation82 then "segmentation82"
    else if segmentation = segmentation83 then "segmentation83"
    else if segmentation = segmentation84 then "segmentation84"
    else if segmentation = segmentation85 then "segmentation85"
    else if segmentation = segmentation86 then "segmentation86"
    else if segmentation = segmentation87 then "segmentation87"
    else if segmentation = segmentation88 then "segmentation88"
    else if segmentation = segmentation89 then "segmentation89"
    else if segmentation = segmentation90 then "segmentation90"
    else if segmentation = segmentation91 then "segmentation91"
    else if segmentation = segmentation92 then "segmentation92"
    else if segmentation = segmentation93 then "segmentation93"
    else if segmentation = segmentation94 then "segmentation94"
    else if segmentation = segmentation95 then "segmentation95"
    else if segmentation = segmentation96 then "segmentation96"
    else if segmentation = segmentation97 then "segmentation97"
    else if segmentation = segmentation98 then "segmentation98"
    else if segmentation = segmentation99 then "segmentation99"
    else if segmentation = segmentation100 then "segmentation100"
    else if segmentation = segmentation101 then "segmentation101"
    else if segmentation = segmentation102 then "segmentation102"
    else if segmentation = segmentation103 then "segmentation103"
    else if segmentation = segmentation104 then "segmentation104"
    else if segmentation = segmentation105 then "segmentation105"
    else if segmentation = segmentation106 then "segmentation106"
    else if segmentation = segmentation107 then "segmentation107"
    else if segmentation = segmentation108 then "segmentation108"
    else if segmentation = segmentation109 then "segmentation109"
    else if segmentation = segmentation110 then "segmentation110"
    else if segmentation = segmentation111 then "segmentation111"
    else if segmentation = segmentation112 then "segmentation112"
    else if segmentation = segmentation113 then "segmentation113"
    else if segmentation = segmentation114 then "segmentation114"
    else if segmentation = segmentation115 then "segmentation115"
    else if segmentation = segmentation116 then "segmentation116"
    else if segmentation = segmentation117 then "segmentation117"
    else if segmentation = segmentation118 then "segmentation118"
    else if segmentation = segmentation119 then "segmentation119"
    else if segmentation = segmentation120 then "segmentation120"
    else if segmentation = segmentation121 then "segmentation121"
    else if segmentation = segmentation122 then "segmentation122"
    else if segmentation = segmentation123 then "segmentation123"
    else if segmentation = segmentation124 then "segmentation124"
    else if segmentation = segmentation125 then "segmentation125"
    else if segmentation = segmentation126 then "segmentation126"
    else if segmentation = segmentation127 then "segmentation127"
    else if segmentation = segmentation128 then "segmentation128"
    else printMap segmentation



let printSet setA =
    let elements =
        setA
        |> Set.map (fun k -> segmentName k)
        |> String.concat ";"
    "Set [" + elements + "]"

let epsilon = 1e-7

let approximatelyEqual (listA,listB) = 
    List.iter2 (fun a b -> Assert.AreEqual(a, b, epsilon)) listA listB

let compareSets (setA,setB) =
    if setA <> setB then 
        Assert.Fail("Expected: " + (printSet setA) + ", Actual: " + (printSet setB))

let compareSegments (segmentA,segmentB) =
    if segmentA <> segmentB then 
        Assert.Fail("Expected: " + (segmentName segmentA) + ", Actual: " + (segmentName segmentB))

let compareMaps (mapA,mapB) =
    if mapA <> mapB then 
        Assert.Fail("Expected: " + (segmentationName mapA) + ", Actual: " + (segmentationName mapB))